config/routes.rb
Rails.application.routes.draw do
  resources :todo_kishans
  resources :todo_items
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/todo_item.rb
class TodoItem < ApplicationRecord
end

app/models/todo_kishan.rb
class TodoKishan < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  before_action :set_todo_item, only: %i[ show edit update destroy ]

  # GET /todo_items or /todo_items.json
  def index
    @todo_items = TodoItem.all
  end

  # GET /todo_items/1 or /todo_items/1.json
  def show
  end

  # GET /todo_items/new
  def new
    @todo_item = TodoItem.new
  end

  # GET /todo_items/1/edit
  def edit
  end

  # POST /todo_items or /todo_items.json
  def create
    @todo_item = TodoItem.new(todo_item_params)

    respond_to do |format|
      if @todo_item.save
        format.html { redirect_to todo_item_url(@todo_item), notice: "Todo item was successfully created." }
        format.json { render :show, status: :created, location: @todo_item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @todo_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_items/1 or /todo_items/1.json
  def update
    respond_to do |format|
      if @todo_item.update(todo_item_params)
        format.html { redirect_to todo_item_url(@todo_item), notice: "Todo item was successfully updated." }
        format.json { render :show, status: :ok, location: @todo_item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @todo_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_items/1 or /todo_items/1.json
  def destroy
    @todo_item.destroy

    respond_to do |format|
      format.html { redirect_to todo_items_url, notice: "Todo item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_item
      @todo_item = TodoItem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def todo_item_params
      params.require(:todo_item).permit(:title)
    end
end

app/controllers/todo_kishans_controller.rb
class TodoKishansController < ApplicationController
  before_action :set_todo_kishan, only: %i[ show edit update destroy ]

  # GET /todo_kishans or /todo_kishans.json
  def index
    @todo_kishans = TodoKishan.all
  end

  # GET /todo_kishans/1 or /todo_kishans/1.json
  def show
  end

  # GET /todo_kishans/new
  def new
    @todo_kishan = TodoKishan.new
  end

  # GET /todo_kishans/1/edit
  def edit
  end

  # POST /todo_kishans or /todo_kishans.json
  def create
    @todo_kishan = TodoKishan.new(todo_kishan_params)

    respond_to do |format|
      if @todo_kishan.save
        format.html { redirect_to todo_kishan_url(@todo_kishan), notice: "Todo kishan was successfully created." }
        format.json { render :show, status: :created, location: @todo_kishan }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @todo_kishan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_kishans/1 or /todo_kishans/1.json
  def update
    respond_to do |format|
      if @todo_kishan.update(todo_kishan_params)
        format.html { redirect_to todo_kishan_url(@todo_kishan), notice: "Todo kishan was successfully updated." }
        format.json { render :show, status: :ok, location: @todo_kishan }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @todo_kishan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_kishans/1 or /todo_kishans/1.json
  def destroy
    @todo_kishan.destroy

    respond_to do |format|
      format.html { redirect_to todo_kishans_url, notice: "Todo kishan was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_kishan
      @todo_kishan = TodoKishan.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def todo_kishan_params
      params.require(:todo_kishan).permit(:title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/helpers/todo_kishans_helper.rb
module TodoKishansHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todo_items/_form.html.erb
<%= form_with(model: todo_item) do |form| %>
  <% if todo_item.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(todo_item.errors.count, "error") %> prohibited this todo_item from being saved:</h2>

      <ul>
        <% todo_item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/todo_items/_todo_item.html.erb
<div id="<%= dom_id todo_item %>">
  <p>
    <strong>Title:</strong>
    <%= todo_item.title %>
  </p>

</div>

app/views/todo_items/edit.html.erb
<h1>Editing todo item</h1>

<%= render "form", todo_item: @todo_item %>

<br>

<div>
  <%= link_to "Show this todo item", @todo_item %> |
  <%= link_to "Back to todo items", todo_items_path %>
</div>

app/views/todo_items/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Todo items</h1>

<div id="todo_items">
  <% @todo_items.each do |todo_item| %>
    <%= render todo_item %>
    <p>
      <%= link_to "Show this todo item", todo_item %>
    </p>
  <% end %>
</div>

<%= link_to "New todo item", new_todo_item_path %>

app/views/todo_items/new.html.erb
<h1>New todo item</h1>

<%= render "form", todo_item: @todo_item %>

<br>

<div>
  <%= link_to "Back to todo items", todo_items_path %>
</div>

app/views/todo_items/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @todo_item %>

<div>
  <%= link_to "Edit this todo item", edit_todo_item_path(@todo_item) %> |
  <%= link_to "Back to todo items", todo_items_path %>

  <%= button_to "Destroy this todo item", @todo_item, method: :delete %>
</div>